### ISSUE TITLE
smf_read_inds_maint update

### ISSUE THREAD

**Issue by qcybb** [sbulen/sjrbTools#2]
Could you please also clean the user entries in "log_notify" and "themes".

Log_notify contains the users watched board/thread notifications and themes contain the users custom theme settings.

**Comment by sbulen** [comment]
My initial thought here is that those should wait until the user is deleted.  

Relatively low volume, & what if they do come back?

The reason I was comfortable cleaning log_boards, log_topics & log_mark_read is that, if a user comes back after being gone a long time, this would be barely noticeable, if at all.  All recent content would look new/unread to them anyway.  It's passive.  

Purging their notification & theme settings reverses actions they have taken.

**Comment by qcybb** [comment]
I completely understand where you are coming from.

The reason I suggested this is that I've been running my forum since 2002 and have a large user base. I have users that haven't logged in for 17 years. It's pretty safe to assume they are never coming back, and would be nice to get rid of all of their board/thread notifications and any theme settings.

What I was hoping for is a new option to handle the later 2 - and maybe just default not to clean those unless it's been 5+ years. I think others would find this useful as well.

Either way you decide, I really appreciate all the hard work you put in to this script. It's easily cleaned out a couple million rows out of my DB. I just have a feeling I've got a few hundred thousand more rows worth of stale notifications/theme settings.

**Comment by sbulen** [comment]
I am going to close this out now for the reasons specified above.
